# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# - repo: https://github.com/asottile/seed-isort-config
#   rev: 'v2.2.0'
#   hooks:
#   - id: seed-isort-config

- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v5.9.1'
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: '22.3.0'
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.0.1'
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: double-quote-string-fixer

- repo: https://github.com/pycqa/flake8  # code
  rev: '3.9.2'
  hooks:
  - id: flake8
    args:
    - --max-line-length=88
    # D106 Missing docstring in public nested class
    # D401 First line should be in imperative mood
    - --extend-ignore=D106,D401
    additional_dependencies:
    - flake8-docstrings
    exclude: ^(migrations/|tests)

- repo: https://github.com/pycqa/flake8  # tests
  rev: '3.9.2'
  hooks:
  - id: flake8
    args:
    - --max-line-length=88
    # E501 Line too long
    - --extend-ignore=D, E501
    additional_dependencies:
    - flake8-docstrings
    exclude: ^(migrations/|app/)

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.910'
  hooks:
  - id: mypy
    # additional_dependencies:
    #   - fastapi==0.65.3
    #   - fastapi-sqlalchemy==0.2.1
    #   - pandas==1.3.0
    #   - psycopg2==2.9.1
    #   - sqlalchemy2-stubs==0.0.2a4
    #   - types-requests==2.25.0
    exclude: ^migrations/
